### ISSUE TITLE
Cannot enable glib library if cross compiling

### ISSUE THREAD

**Issue by rossburton** [libical/libical#394]
The `src-generator` binary is built with the target compiler so can't be run during the build:

```
| /bin/sh: 1: [...]/build/bin/src-generator: Exec format error
```

```
$ file bin/src-generator
bin/src-generator: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, not stripped
$ uname -a
Linux flashheart 4.19.0-0.bpo.4-amd64 #1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27) x86_64 GNU/Linux
```

That binary should be built using the host compiler, not the target compiler.

**Comment by winterz** [comment]
thanks for the report.
for now you should be able to pass -DICAL_GLIB=False to cmake .  I doubt you need the libical-glib library.

**Comment by winterz** [comment]
We just committed some fixes for building with gtk.  could you test?  both the master branch or the 3.0 branch have the fix.

**Comment by winterz** [comment]
we released v3.0.6 today.
please test if this is fixed.

**Comment by rossburton** [comment]
Apologies for not testing sooner.

```
| /bin/sh: 1: /data/poky-tmp/master/work/armv7vet2hf-neon-poky-linux-gnueabi/libical/3.0.6-r0/build/bin/src-generator: Exec format error
```

```
$ file src-generator
src-generator: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=9f8ee30a1df80a2c0794f049563fb568d1da7f5c, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Still being built with the cross compiler instead of the native compiler.

**Comment by rossburton** [comment]
FWIW still happens with 3.0.7:
```
| /bin/sh: 1: /data/poky-tmp/master/work/armv7vet2hf-neon-poky-linux-gnueabi/libical/3.0.7-r0/build/bin/src-generator: Exec format error
```

`src-generator` was built with the cross compiler, not the host compiler.

Have you considered moving to Meson, which handles this trivially?

**Comment by triffid** [comment]
I just ran into this issue in 3.0.8

**Comment by winterz** [comment]
should be solved in commit 1197d84b63dce179b55a6293cfd6d0523607baf1
in the 3.0 and master branches

**Comment by kanavin** [comment]
How is the code in that commit supposed to work? I am getting:
```
| CMake Error at src/libical-glib/CMakeLists.txt:81 (include):
|   include could not find load file:
| 
|     ICAL_GLIB_SRC_GENERATOR-NOTFOUND
```
when cross-compiling. Am I missing something?

**Comment by kanavin** [comment]
Filed a separate issue:
https://github.com/libical/libical/issues/481
